before_install:
- brew update
- brew install openssl
- brew install libevent

script:
- make
- make clean

anchors:
  - &run-high_sierra
    os: osx
    osx_image: xcode9.3beta
    env:
    - BUILD_OS_VERSION=high_sierra
    - REDSOCKS_FORMULA_FILE=redsocks2.rb
  - &run-sierra
    os: osx
    osx_image: xcode9.2
    env:
    - BUILD_OS_VERSION=sierra
    - REDSOCKS_FORMULA_FILE=redsocks2.rb
  - &run-el_capitan
    os: osx
    osx_image: xcode8
    env:
    - BUILD_OS_VERSION=el_capitan
    - REDSOCKS_FORMULA_FILE=redsocks2.rb
  - &bottleit
    before_install:
    - brew update
    - brew install openssl
    - brew install libevent
    # set up awscli packages
    - brew install awscli
    - mkdir -p build
    - aws s3 sync s3://travis-redsocks/$TRAVIS_BUILD_NUMBER build/
    script:
    - cd build
    # - ls -lahR .
    - brew install --build-bottle ./${REDSOCKS_FORMULA_FILE}
    - sed -i '' '/root_url/d' ./${REDSOCKS_FORMULA_FILE}
    - brew bottle --verbose --json --force-core-tap --root_url=https://github.com/VixsTy/redsocks/releases/download/${TRAVIS_TAG} ./${REDSOCKS_FORMULA_FILE}
    - brew bottle --merge --write --no-commit --keep-old redsocks2-${TRAVIS_TAG}.${BUILD_OS_VERSION}.bottle.json
    after_success:
    - aws s3 sync . s3://travis-redsocks/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: build
      if: tag IS blank
      language: c
      <<: *run-high_sierra
    - stage: build
      language: c
      if: tag IS blank
      <<: *run-sierra
    - stage: build
      if: tag IS blank
      language: c
      <<: *run-el_capitan

    - stage: prepare-brew-formula
      if: tag IS present
      env:
      - REDSOCKS_FORMULA_FILE=redsocks2.rb
      before_install:
      # set up awscli packages
      - pip install --user awscli
      - mkdir -p build
      - aws s3 sync s3://travis-redsocks/$TRAVIS_BUILD_NUMBER build/
      script:
      - sed 's|{{tags}}|'${TRAVIS_TAG}'|' darwin-xnu/homebrew/redsocks2.rb > build/${REDSOCKS_FORMULA_FILE}
      after_success:
      - aws s3 sync build/ s3://travis-redsocks/$TRAVIS_BUILD_NUMBER

    - stage: bottleit-high_sierra
      if: tag IS present
      <<: *run-high_sierra
      <<: *bottleit
    - stage: bottleit-sierra
      if: tag IS present
      <<: *run-sierra
      <<: *bottleit
    - stage: bottleit-el_capitan
      if: tag IS present
      <<: *run-el_capitan
      <<: *bottleit

    # - stage: print-workspace
    #   before_install:
    #   <<: *awss3
    #   script: ls -lahR .

    - stage: deploy
      if: tag IS present
      before_install:
      # set up awscli packages
      - pip install --user awscli
      - mkdir -p build
      - aws s3 sync s3://travis-redsocks/$TRAVIS_BUILD_NUMBER build/
      script: skip
      deploy:
        provider: releases
        api_key:
          secure: RLj2Mh5/HwuTozWHkrzQLiGJs/PfMPQgkoH7nuoD/1fm1AvpuAKbhHtok2r4x9yTJ8rnkU5yOEG6gu7akEJCV8C+Cmy/VpA1nZa1ZyWoUeA2PfiAu4Vmv3es53ZB0AS4E95mTcPo8J3w40MRaiZPauzK9h2kXS3Hmg7V16ULHHFAZK+CS+4Vr/WthmHbYZjxtK8XN2ahnMt49bGuOyBflJy6rknJ+1DsOtVTHjVUPY0upGLc8MQQmhNFIv2s8dtx3CuhsTomg7gtAfvAIks1CFGLmPCMhIkcQrn+cdHEUZ9G6pthAr8sOwHLlz1/3uj7F0F875RBMlsRh69maPTMipX5wELt73FfiGEuRRxftfc2rPGNw+jJi7G45lqxkFWeVenfrel5J5oXHmJxCsnYbkUozUfhJTq2OCZcjR54elX4q9UNFfR/ksmm67qE7MkqmlBHvp1ZySk/fwp8qBsFztGDsPE2o6ClMwZC8nvYdFgLSlzD3U+lN65p/hOitoeudV5rZ83Ul52VPjbIy3U1Jze6WkkqmzUDkcRWyUJVFMrsPTF1k/sEcsBhOvXULtFaZXFY7RKg5hNfki7R/fcykKVsvv+vtTzJ9DSa97d1L/B6ZrU2SbJ8ecxz0Z6SAWytvvvJ0qo4tayIT9/9Ka9KmM7WhIVbwIuv9mg6LPOQfUg=
        file_glob: true
        file:
        - "build/*"
        skip_cleanup: true
        on:
          tags: true

    - stage: push formula
      if: tag IS present
      before_install:
      # set up awscli packages
      - pip install --user awscli
      - mkdir -p build
      - aws s3 sync s3://travis-redsocks/$TRAVIS_BUILD_NUMBER build/
      script:
      - git config --global user.email "travis@travis-ci.org"
      - git config --global user.name "Travis CI"
      - git clone https://${GH_TOKEN}@github.com/VixsTy/homebrew-redsocks2.git homebrew-redsocks2
      - cp build/${REDSOCKS_FORMULA_FILE} homebrew-redsocks2/
      - cd homebrew-redsocks2
      - git commit --message "Travis build ${TRAVIS_BUILD_NUMBER} set version to ${TRAVIS_TAG}" ${REDSOCKS_FORMULA_FILE}
      - git push https://${GH_TOKEN}@github.com/VixsTy/homebrew-redsocks2.git
      after_success:
      - aws s3 rm --recursive s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER # clean up after ourselves
