language: c

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8

before_install:
  - brew update
  - brew install openssl
  - brew install libevent

script:
  - make

deploy:
  provider: releases
  api_key: "b62932437283f44aef283c83a617b66c61c85ca4"
  file:
    - "redsocks2"
    - "debian/redsocks.8"
    - "darwin-xnu/redsocks.conf"
  skip_cleanup: true
  on:
    tags: true
